### ISSUE TITLE
KeyError: 'LINE_OFF'

### ISSUE THREAD

**Issue by mjstroud** [cmla/s2p#25]
Hello,

I am running into the following error while trying to run s2p on a pair of input images. I have tried running with and without RPCs (XML files), and have tried with and without ROI specification. Any suggestions?

Traceback (most recent call last):
  File "/usr/local/bin/s2p", line 11, in <module>
    load_entry_point('s2p', 'console_scripts', 's2p')()
  File "/root/s2p/s2p/cli.py", line 22, in main
    s2p.main(user_cfg)
  File "/root/s2p/s2p/__init__.py", line 568, in main
    initialization.build_cfg(user_cfg)
  File "/root/s2p/s2p/initialization.py", line 113, in build_cfg
    check_parameters(user_cfg)
  File "/root/s2p/s2p/initialization.py", line 58, in check_parameters
    img['rpc'] = rpcm.rpc_from_geotiff(img['img'])
  File "/usr/local/lib/python3.5/dist-packages/rpcm/rpc_model.py", line 70, in rpc_from_geotiff
    return RPCModel(rpc_dict)
  File "/usr/local/lib/python3.5/dist-packages/rpcm/rpc_model.py", line 93, in __init__
    self.row_offset = float(d['LINE_OFF'])
KeyError: 'LINE_OFF'

**Comment by carlodef** [comment]
Hello @mjstroud, could you please provide the input files so that your issue can be reproduced?

**Comment by mjstroud** [comment]
Sorry @carlodef for the snag here, unfortunately I cannot provide the input files as they are classified. I understand that makes it a bit more difficult to troubleshoot the error, but if you have any suggestions I would still appreciate it.

To help simplify, I used a config from the input_pair sample, replaced the test images with my own .tif files, and changed the full_img parameter to true. I run 's2p config.json', and get error from above.

> Hello @mjstroud, could you please provide the input files so that your issue can be reproduced?

**Comment by gfacciol** [comment]
Dear @mjstroud,
The problem is that rasterio/gdal is failing to read the RPC information from the XML sidecar. 
The RPC filenames must follow specific conventions for gdal to read them.

For Ikonos-type (txt) RPC files the following conventions for RPC files are applied:
- filename.tif
- filename_rpc.txt 

For XML RPC's the conventions used by gdal depend on the specific  provider. For instance pleiades images expect this format:
- IMG_PHR1B_P_201306181350386_SEN_629608101-001_R1C1.{TIF|JP2} 
- RPC_PHR1B_P_201306181350386_SEN_629608101-001.XML

What is the provider of your images? Can you copy the filenames?

**Comment by mjstroud** [comment]
@gfacciol We are currently using Digital Globe WorldView data. The filenames are provided in the following format.

102001002138EC00.r100.tif
102001002138EC00.r100.xml
-and-
1020010021AA3000.r100.tif
1020010021AA3000.r100.xml

**Comment by gfacciol** [comment]
Dear @mjstroud, 
commit  39c8258 just solved this issue, now you can specify the image with and rpc in the json file as:

 "images": [
    {
      "img": "=im1.tif",
      "rpc": "rpc1.txt"
    },
    {
      "img": "im2.tif",
      "rpc": "rpc2.txt"
    }
  ],
