### ISSUE TITLE
Why the pointing error matrix is used instead of bias-compensated rpcs?

### ISSUE THREAD

**Issue by lauraset** [cmla/s2p#46]
Dear Carlodef,
  In the s2p software, the pointing error matrix is used for correcting the rpc bias. It works well for a stereo pair, but not for multitemporal stereo pair. Why not use bias-compensated rpcs? In this way, the images with refined rpcs can be used for other software easily.  Besides, in the paper-_Automatic 3D Reconstruction from Multi-Date Satellite Images_, a bias correction offset was used for aligning the multi-date images. Does it refer to the pointing error matrix in the s2p software? Could you provide detailed explanations?
  Thank you very much.
Best regards,
Yinxia Cao

**Comment by gfacciol** [comment]
Dear Yinxia Cao, 

Indeed, applying a 'bundle adjustment' (BA) to correct the rpcs of a set of images would have the same effect as the correction do in s2p apply. It would amount to adjust the 3D orientation of the satellites. 
The correction we apply for a pair of images in s2p is called 'bundle block adjustment' [Grodecki and Dial 2003]  and the difference wrt BA is that it is applied in image space instead of 3D. The difference is explained in the paper below (see: eq. 2 and 3 in the poster). 

> Marí, R., de Franchis, C., Meinhardt-Llopis, E., & Facciolo, G. (2019). To Bundle Adjust or Not: A Comparison of Relative Geolocation Correction Strategies for Satellite Multi-View Stereo. In Proceedings of the IEEE International Conference on Computer Vision Workshops     https://rogermm14.github.io/bundle-adjust-or-not/ 

In the paper "Automatic 3D Reconstruction from Multi-Date Satellite Images",  we use the bundle block adjustment of s2p on each pair.  We then we align the triangulated DSMs (this is justified by a property of the affine cameras). This is detailed in the section 'Correlation based DSM alignment' of our paper [Mari et al. 2019], where we also compare the three techniques. 


Best, 
Gabriele
